language: scala

scala:
  - 2.11.13
  - 2.12.7

jdk:
  - oraclejdk8

matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.6

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt -scala-version $TRAVIS_SCALA_VERSION ';clean; testOnly -- timefactor 5 exclude travis'
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
